"""empty message

Revision ID: 706c27850ffc
Revises: 
Create Date: 2023-08-05 05:57:15.436853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "706c27850ffc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_login_info",
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("email_id", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("record_start_date", sa.DateTime(), nullable=True),
        sa.Column("record_end_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("email_id"),
        schema="cancer_screener",
    )
    op.drop_index("DjangoApp_menu_category_id_id_95c23f6f", table_name="DjangoApp_menu")
    op.drop_table("DjangoApp_menu")
    op.drop_index(
        "django_admin_log_content_type_id_c4bce8eb", table_name="django_admin_log"
    )
    op.drop_index("django_admin_log_user_id_c564eba6", table_name="django_admin_log")
    op.drop_table("django_admin_log")
    op.drop_table("Teacher")
    op.drop_table("django_migrations")
    op.drop_index("django_session_expire_date_a5c62663", table_name="django_session")
    op.drop_index(
        "django_session_session_key_c0390e0f_like", table_name="django_session"
    )
    op.drop_table("django_session")
    op.drop_index(
        "auth_group_permissions_group_id_b120cbf9", table_name="auth_group_permissions"
    )
    op.drop_index(
        "auth_group_permissions_permission_id_84c5c92e",
        table_name="auth_group_permissions",
    )
    op.drop_table("auth_group_permissions")
    op.drop_index("auth_user_groups_group_id_97559544", table_name="auth_user_groups")
    op.drop_index("auth_user_groups_user_id_6a12ed8b", table_name="auth_user_groups")
    op.drop_table("auth_user_groups")
    op.drop_index("auth_group_name_a6ea08ec_like", table_name="auth_group")
    op.drop_table("auth_group")
    op.drop_table("student")
    op.drop_index("auth_user_username_6821ab7c_like", table_name="auth_user")
    op.drop_table("auth_user")
    op.drop_table("DjangoApp_reservation")
    op.drop_index(
        "auth_permission_content_type_id_2f476e4b", table_name="auth_permission"
    )
    op.drop_table("auth_permission")
    op.drop_table("DjangoApp_menucategory")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DjangoApp_menucategory",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "menu_category_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="DjangoApp_menucategory_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "auth_permission",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("content_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "codename", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
            name="auth_permission_content_type_id_2f476e4b_fk_django_co",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="auth_permission_pkey"),
        sa.UniqueConstraint(
            "content_type_id",
            "codename",
            name="auth_permission_content_type_id_codename_01ab375a_uniq",
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "auth_permission_content_type_id_2f476e4b",
        "auth_permission",
        ["content_type_id"],
        unique=False,
    )
    op.create_table(
        "DjangoApp_reservation",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "contact", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column("time", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="DjangoApp_reservation_pkey"),
    )
    op.create_table(
        "auth_user",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "password", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "first_name", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_name", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=254), autoincrement=False, nullable=False),
        sa.Column("is_staff", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "date_joined",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="auth_user_pkey"),
        sa.UniqueConstraint("username", name="auth_user_username_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "auth_user_username_6821ab7c_like", "auth_user", ["username"], unique=False
    )
    op.create_table(
        "student",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("grade", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="student_pkey"),
    )
    op.create_table(
        "auth_group",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="auth_group_pkey"),
        sa.UniqueConstraint("name", name="auth_group_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "auth_group_name_a6ea08ec_like", "auth_group", ["name"], unique=False
    )
    op.create_table(
        "auth_user_groups",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
            name="auth_user_groups_group_id_97559544_fk_auth_group_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name="auth_user_groups_user_id_6a12ed8b_fk_auth_user_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="auth_user_groups_pkey"),
        sa.UniqueConstraint(
            "user_id",
            "group_id",
            name="auth_user_groups_user_id_group_id_94350c0c_uniq",
        ),
    )
    op.create_index(
        "auth_user_groups_user_id_6a12ed8b",
        "auth_user_groups",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "auth_user_groups_group_id_97559544",
        "auth_user_groups",
        ["group_id"],
        unique=False,
    )
    op.create_table(
        "auth_group_permissions",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
            name="auth_group_permissions_group_id_b120cbf9_fk_auth_group_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["auth_permission.id"],
            name="auth_group_permissio_permission_id_84c5c92e_fk_auth_perm",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="auth_group_permissions_pkey"),
        sa.UniqueConstraint(
            "group_id",
            "permission_id",
            name="auth_group_permissions_group_id_permission_id_0cd325b0_uniq",
        ),
    )
    op.create_index(
        "auth_group_permissions_permission_id_84c5c92e",
        "auth_group_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        "auth_group_permissions_group_id_b120cbf9",
        "auth_group_permissions",
        ["group_id"],
        unique=False,
    )
    op.create_table(
        "django_session",
        sa.Column(
            "session_key", sa.VARCHAR(length=40), autoincrement=False, nullable=False
        ),
        sa.Column("session_data", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expire_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("session_key", name="django_session_pkey"),
    )
    op.create_index(
        "django_session_session_key_c0390e0f_like",
        "django_session",
        ["session_key"],
        unique=False,
    )
    op.create_index(
        "django_session_expire_date_a5c62663",
        "django_session",
        ["expire_date"],
        unique=False,
    )
    op.create_table(
        "django_migrations",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("app", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "applied",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="django_migrations_pkey"),
    )
    op.create_table(
        "Teacher",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"Teacher_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("firstName", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("lastName", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "createdAt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="Teacher_pkey"),
    )
    op.create_table(
        "django_content_type",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "app_label", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("model", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="django_content_type_pkey"),
        sa.UniqueConstraint(
            "app_label",
            "model",
            name="django_content_type_app_label_model_76bd3d3b_uniq",
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "django_admin_log",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "action_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("object_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "object_repr", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("action_flag", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("change_message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "action_flag >= 0", name="django_admin_log_action_flag_check"
        ),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
            name="django_admin_log_content_type_id_c4bce8eb_fk_django_co",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name="django_admin_log_user_id_c564eba6_fk_auth_user_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="django_admin_log_pkey"),
    )
    op.create_index(
        "django_admin_log_user_id_c564eba6",
        "django_admin_log",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "django_admin_log_content_type_id_c4bce8eb",
        "django_admin_log",
        ["content_type_id"],
        unique=False,
    )
    op.create_table(
        "DjangoApp_menu",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "cuisine", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category_id_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id_id"],
            ["DjangoApp_menucategory.id"],
            name="DjangoApp_menu_category_id_id_95c23f6f_fk_DjangoApp",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="DjangoApp_menu_pkey"),
    )
    op.create_index(
        "DjangoApp_menu_category_id_id_95c23f6f",
        "DjangoApp_menu",
        ["category_id_id"],
        unique=False,
    )
    op.drop_table("user_login_info", schema="cancer_screener")
    # ### end Alembic commands ###
